[package]
name = "rough"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { default-features = false, version = "0.11.0" }
regex = { default-features = false, version = "1.9.1", features = ["unicode-perl"] }
rug = { version = "1.20.0", features = ["num-traits"] }

[profile.release]
lto = "fat"
