[package]
name = "rough"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
itertools = "0.11.0"
regex = { default-features = false, version = "1.9.1", features = ["unicode-perl"] }
serde = { default-features = false, version = "1.0.180", features = ["derive"]  }
serde_json = "1.0.104"

[profile.release]
lto = "fat"
codegen-units = 1
debug = false
