[package]
name = "rough"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circular-buffer = "0.1.1"
fxhash = "0.2.1"
itertools = "0.11.0"
petgraph = { default-features = false, version = "0.6.3" }
regex = { default-features = false, version = "1.9.1", features = ["unicode-perl"] }
rug = { version = "1.20.0", features = ["rand"], default-features = false }
serde = { version = "1.0.180", features = ["derive"], default-features = false }
serde_json = "1.0.104"
symbolic_math = "0.1.1"

[profile.release]
lto = "fat"
