[build]
rustflags = ["-C", "target-cpu=native"]

[alias]
rr = "run --release"
br = "build --release"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=/usr/bin/mold"
]